spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        min-idle: 0
        max-idle: 8

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/redis
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        open-in-view: false


    hibernate:
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
    generate-ddl: true